import type { JobListing } from '@/components/cards/JobCard'

export const JOB_LISTINGS: JobListing[] = [
  {
    id: 'JOB-2024-001',
    title: 'Human Resources Manager',
    location: 'Sunnyvale, CA',
    salary: '$44,000–$55,000/yr',
    experience: '1–3 Years Exp',
    type: 'Direct Hire',
    postedAgo: '2 days ago',
    companyInitials: 'AC',
  },
  {
    id: 'JOB-2024-002',
    title: 'Software Engineer',
    location: 'San Francisco, CA',
    salary: '$85,000–$90,000/yr',
    experience: '3–5 Years Exp',
    type: 'Contract to Hire',
    postedAgo: '3 days ago',
    companyInitials: 'SF',
  },
  {
    id: 'JOB-2024-003',
    title: 'Administrative Coordinator',
    location: 'Boston, MA',
    salary: '$62,000–$75,000/yr',
    experience: 'Entry Level',
    type: 'Contract',
    postedAgo: '5 days ago',
    companyInitials: 'BT',
  },
  {
    id: 'JOB-2024-004',
    title: 'Talent Acquisition Specialist',
    location: 'San Francisco, CA',
    salary: '$85,000–$90,000/yr',
    experience: '3–5 Years Exp',
    type: 'Contract to Hire',
    postedAgo: '1 week ago',
    companyInitials: 'HR',
  },
  {
    id: 'JOB-2024-005',
    title: 'Business Analyst',
    location: 'Sunnyvale, CA',
    salary: '$44,000–$55,000/yr',
    experience: '3–5 Years Exp',
    type: 'Direct Hire',
    postedAgo: '1 week ago',
    companyInitials: 'BA',
  },
  {
    id: 'JOB-2024-006',
    title: 'DevOps Engineer',
    location: 'San Francisco, CA',
    salary: '$85,000–$90,000/yr',
    experience: '3–5 Years Exp',
    type: 'Contract to Hire',
    postedAgo: '2 weeks ago',
    companyInitials: 'DO',
  },
  {
    id: 'JOB-2024-007',
    title: 'Data Scientist',
    location: 'New York, NY',
    salary: '$95,000–$110,000/yr',
    experience: '3–5 Years Exp',
    type: 'Direct Hire',
    postedAgo: '3 days ago',
    companyInitials: 'DS',
  },
  {
    id: 'JOB-2024-008',
    title: 'Financial Analyst',
    location: 'Chicago, IL',
    salary: '$65,000–$78,000/yr',
    experience: '1–3 Years Exp',
    type: 'Direct Hire',
    postedAgo: '4 days ago',
    companyInitials: 'FN',
  },
]

export const JOB_CATEGORIES = [
  'All',
  'IT',
  'HR',
  'Finance',
  'Engineering',
  'Admin',
  'Executive',
] as const

export const WORK_STATUS_FILTERS = [
  'All',
  'Full-Time',
  'Contract',
  'Part-Time',
  'C2C',
] as const
